IVGCVSW-5261 Fix undefined reference to GetIdStatic()
 * Moved DynamicBackend tests to only build when ArmnnRef is enabled
   due to a dependency on them dynamically loading the ArmnnRef backend
   object

Signed-off-by: David Monahan <david.monahan@arm.com>
Change-Id: Iee0480e7d0cf505bbb5c26629829d3d20fb60051