IVGCVSW-4582 Undefined reference to GetProfilingService causes failure in the Backends CI job
* Enable the GetProfilingService() function to BackendProfilingTests and ProfilingTestUtils

Signed-off-by: Sadik Armagan <sadik.armagan@arm.com>
Change-Id: I32e3625db0f465883f2ec27fb7c2fad4e91b6306