MLCE-121 Github: Build error on GCC 9
 * Fixed an error encountered when building on GCC 9
   error: moving a local object in a return statement prevents copy elision
 * Fixed failures in unit tests due to std::initializer_list handling in GCC 9

Change-Id: I4bfdd2113dfedcecd29479ee556e4ae22278755d
Signed-off-by: Mike Kelly <mike.kelly@arm.com>