Add missing includes of cstdint
This avoids the following error and many more like it when building with
GCC 15:

  In file included from src/armnn/BackendRegistry.cpp:8:
  include/armnn/profiling/ArmNNProfiling.hpp:16:14: error: 'uint16_t'
  does not name a type
     16 | static const uint16_t NETWORK_LOADS         = 0;
        |              ^~~~~~~~
  include/armnn/profiling/ArmNNProfiling.hpp:9:1: note: 'uint16_t' is
  defined in header '<cstdint>'; this is probably fixable by adding
  '#include <cstdint>'
      8 | #include <armnn/Version.hpp>
    +++ |+#include <cstdint>
      9 |

Change-Id: Ie1706e0af1d8004467d3a6055ffa1e97930f0eaf
Signed-off-by: Peter Kjellerstedt <pkj@axis.com>